Sprint2/step2
OlesiaPolevoi/react-burger pull request #5
Opened 2022-11-20 23:40 UTC by OlesiaPolevoi

2022-11-21 03:39 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Реализована работа с redux;
- Реализован функционал с DnD;

### **Но есть несколько замечаний, которые нужно исправить:**

- Запрос `POST /order` должен уходить только тогда, когда в burger-constructor есть и булка и хотя бы 1 ингредиент.

- При отправке запроса на создание заказа `POST /orders`, в поле `ingredients` следует передавать обе булки, а не 1. Т.е. id булок должны быть в самом начале массива, и в конце, а также они должны быть одинаковы: https://yadi.sk/d/zkBeMzVexhQGSg;

- следует разделить экшены по файлам, на нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктор. Лучше, что бы экшены относящиеся к решению каждой были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавлять новый функционал и плохо, если придется все экшены описывать в одном файле, он будет слишком большой;

  В текущем приложении можно разделить на следующие файлы:

  - загрузка данных ингредиентов
  - работа конструктора
  - открытие ингредиента в попапе
  - оформление заказа

- со временем приложение будет разрастаться, появится новый функционал, если все будет в одном рельюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например

  - загрузка данных ингредиентов
  - отправка заказа
  - работа конструктора
  - открытие модального окна ингредиента

  Для объединения редьюсеров используйте combineReducers
  https://redux.js.org/api/combinereducers

- По чек-листу, у вас должен быть подключён Redux Devtools, который будет работать только в `dev` режиме.

- По чек-листу, хранилище должно иметь объект текущего просматриваемого ингредиента.

- Необходимо указывать .isRequired у ингредиента в propTypes. (`ingredientDetails`)

- У вас неправильно описана структура ингредиента, там намного больше полей.

- У вас некорректно реализована работа с Dnd:

  - Элементы не меняют своего положения: https://disk.yandex.ru/i/vcvM34xKlrLYww, как это должно быть: https://disk.yandex.ru/i/7gFf2HTpHeq5Dg;

### **Сделает код лучше:**

- Не стоит писать в 1 файле, много компонентов, в будущем это может осложнить рефакторинг и масштабирование приложения.

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-11-21 03:39 UTC, ArslanDev666 commented on src/services/reducers/index.js
> +          }
**Можно лучше:**

Тут можно объединить в 1 проверку, используя тернарный оператор.

2022-11-21 03:39 UTC, ArslanDev666 commented on src/services/reducers/index.js
> +            el["orderedQuantity"] = 2;
**Можно лучще:**

Здесь и далее, почему бы не писать поле обьекта через `.` - `el.orderedQuantity`.

2022-11-21 03:39 UTC, ArslanDev666 commented on src/components/burgerConstructor/burger-constructor.jsx
> +const InnerIngredient = ({ index, el }) => {
**Надо исправить:**

для этого компонента так же нужно описать PropTypes

2022-11-21 03:39 UTC, ArslanDev666 commented on src/components/burgerConstructor/burger-constructor.jsx
> +  outerBun: PropTypes.object,
**Надо исправить:**

Необходимо полное описание структуры, а не PropTypes.object или PropTypes.array, так же необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
bun: ingredientTypes.isRequired;

ingredients: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
```

2022-11-21 03:39 UTC, ArslanDev666 commented on src/components/burgerIngredients/burger-ingredients.jsx
>  IngredientsContainer.propTypes = {
**Надо исправить:**

Описаны не все propTypes, которые используются в компоненте.

2022-11-21 03:39 UTC, ArslanDev666 commented on src/services/actions/index.js
> +export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
**Можно лучше:**

Лучше сменить `USER` на более подходящее, например на `INGREDIENTS`

2022-11-21 23:49 UTC, OlesiaPolevoi commented on src/components/burgerIngredients/burger-ingredients.jsx
>  IngredientsContainer.propTypes = {
Я не получаю никаких пропсов в BurgerIngredients компоненте 
Данные из хранилища Redux

2022-11-22 02:15 UTC, ArslanDev666 commented on src/components/burgerIngredients/burger-ingredients.jsx
>  IngredientsContainer.propTypes = {
Действительно, тогда замечание отменяется :)
 
 Но не забудьте у `IngredientsContainer` поправить propTypes (выше было замечание про PropTypes.array).

2022-11-22 02:18 UTC, ArslanMustafin commented on src/components/burgerIngredients/burger-ingredients.jsx
>  IngredientsContainer.propTypes = {
Ну и за одно можно поправить `Ingredient.propTypes`, там просто указать `isRequired`.

2022-11-22 10:46 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Была проделана отличная работа над замечаниями 🔥

Все замечания с прошлого ревью были исправлены.

### **Вы молодец!**

### **Но есть несколько новых замечаний, которые нужно исправить:**

- У вас неправильно описана структура ингредиента, там намного больше полей.

  вот корректное описание ингредиента.

  ```js
  export const ingredientPropType = PropTypes.shape({
    _id: PropTypes.string.isRequired,
    name: PropTypes.string.isRequired,
    type: PropTypes.oneOf(["bun", "main", "sauce"]).isRequired,
    proteins: PropTypes.number.isRequired,
    fat: PropTypes.number.isRequired,
    carbohydrates: PropTypes.number.isRequired,
    calories: PropTypes.number.isRequired,
    price: PropTypes.number.isRequired,
    image: PropTypes.string.isRequired,
    image_large: PropTypes.string.isRequired,
    image_mobile: PropTypes.string.isRequired,
  });
  ```

- Если данных нет, то следует записывать null а не пустой объект (Описал подробнее в коде)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-11-22 10:46 UTC, ArslanDev666 commented on src/services/reducers/ingredient-details.js
> +const defaultIngredientState = {};
**Надо исправить:**

Если данных нет, то следует записывать null а не пустой объект.

2022-11-22 10:46 UTC, ArslanDev666 commented on src/services/reducers/ingredient-details.js
> +      return {};
Тут тоже не забудьте поменять))

2022-11-23 05:06 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Все замечания с прошлого ревью были исправлены.

### **Вы молодец!🔥 Работа принята, удачи в дальнейшем обучении.**

2022-11-23 14:10 UTC, merged